# Generated by Django 4.0.5 on 2022-06-14 11:13

import core.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_firstname_remove_user_lastname_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.managers.UserManager()),
            ],
        ),
    ]
